# Generated by Django 5.2 on 2025-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoriqueCalcul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.IntegerField()),
                ("date_calcul", models.DateTimeField(auto_now_add=True)),
                ("est_pair", models.BooleanField()),
                ("est_premier", models.BooleanField()),
                ("binaire", models.CharField(max_length=100)),
                ("hexadecimal", models.CharField(max_length=100)),
                ("racine_carree", models.FloatField(null=True)),
                ("diviseurs", models.JSONField()),
                ("est_fibonacci", models.BooleanField()),
                ("chiffre_romain", models.CharField(max_length=50)),
                ("somme_chiffres", models.IntegerField()),
                ("est_carre_parfait", models.BooleanField()),
                ("est_cube_parfait", models.BooleanField()),
                ("log_base10", models.FloatField(null=True)),
                ("puissance_de_deux", models.BooleanField()),
                ("nombre_chiffres", models.IntegerField()),
                ("est_abondant", models.BooleanField()),
                ("est_palindrome", models.BooleanField()),
                ("factorisation_premiers", models.JSONField()),
            ],
            options={
                "verbose_name": "Historique de calcul",
                "verbose_name_plural": "Historiques de calculs",
                "ordering": ["-date_calcul"],
            },
        ),
    ]
