# Generated by Django 5.2 on 2025-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historiquecalcul",
            name="chiffre_arabe",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="complexe",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="entier_naturel",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="entier_negatif",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="entier_positif",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="entier_relatif",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="imaginaire_pur",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="irrationnel",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="nombre_decimal",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="rationnel",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historiquecalcul",
            name="reel",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
